# path or URL to sample sheet (TSV format, columns: sample, condition, ...)
samples: samples.tsv
# path or URL to sequencing unit sheet (TSV format, columns: sample, unit, fq1, fq2)
# Units are technical replicates (e.g. lanes, or resequencing of the same biological
# sample).
units: units.tsv

#path to the read files
input_folder: data/reads

#the sequencing adapter
adapter: ACGGATCGATCGATCGATCGAT

ref:
  # the STAR index file
  index: "data/input/starindex"
  # gtf file with transcripts
  annotation: "data/input/genesAnnotations.gtf"
pca:
  labels:
    # columns of sample sheet to use for PCA
    - nutrition
    - lifestyle
    - disease
    
diffexp:
  # TODO -> infer from data
  variables:
    - nutrition
    - lifestyle
    - disease
  contrasts:
    FreeRangeVSZoo:
      - lifestyle
      - freerange
      - zoo
  # analyze more complex interactions
  interactions:
    NutritionWhenSickAndZoo:
      environment:
        lifestyle: zoo
        disease: deathelixir
      contrast:
        - nutrition
        - normal
        - carrotsonly
    EffectOfZooOnSickUnicorns:
      environment:
        disease: deathelixir
      contrast:
        - lifestyle
        - zoo
        - freerange
params:
  star: ""
  cutadapt-se: ""
  cutadapt-pe: ""
