$schema: "https://json-schema.org/draft-07/schema#"

description: snakemake configuration file

type: object

properties:

  samples:
    type: string
    
  units:
    type: string
    
  input_folder:
    type: string
    
  adapter:
    type: string
    pattern: "^[ACGT]+$"

  ref:
    type: object
    properties:
      index:
        type: string
      annotation:
        type: string
    required:
      - index
      - annotation

  pca:
    type: object
    properties:
      labels:
        type: array
        items:
          type: string
    required:
      - labels

  diffexp:
    type: object
    properties:
      variables:
        type: array
        items:
          type: string
      contrasts:
        type: object
      interactions:
        type: object
        properties:
          environment:
            type : object
          contrast:
            type: array
            items:
              type: string
            minItems : 3
            maxItems : 3
          required:
            - contrast
            - environment
      required:
        anyOf:
          - contrasts
          - interactions

  params:
    type: object
    properties:
      star: 
        type: string
      cutadapt-se:
        type: string
      cutadapt-pe:
        type: string
    required:
      - star
      - cutadapt-se
      - cutadapt-pe

required:
  - samples
  - units
  - adapter
  - ref
  - pca
  - diffexp
  - params
